
import { Language, Product, TranslationStrings, ThemeColor } from './types';

export const LANGUAGES = [
  { code: Language.EN, label: 'English', flag: '🇺🇸', currency: 'USD' },
  { code: Language.KH, label: 'ភាសាខ្មែរ', flag: '🇰🇭', currency: 'KHR' },
  { code: Language.CN, label: '中文', flag: '🇨🇳', currency: 'CNY' },
];

export const THEMES: Record<ThemeColor, { primary: string; hover: string; text: string; bgLight: string; border: string }> = {
  black: { primary: 'bg-black', hover: 'hover:bg-gray-900', text: 'text-black', bgLight: 'bg-gray-100', border: 'border-black' },
  red: { primary: 'bg-[#d0011b]', hover: 'hover:bg-[#b00116]', text: 'text-[#d0011b]', bgLight: 'bg-red-50', border: 'border-[#d0011b]' },
  blue: { primary: 'bg-[#1E3A8A]', hover: 'hover:bg-[#152a6a]', text: 'text-[#1E3A8A]', bgLight: 'bg-blue-50', border: 'border-[#1E3A8A]' },
  gold: { primary: 'bg-[#b8860b]', hover: 'hover:bg-[#996515]', text: 'text-[#b8860b]', bgLight: 'bg-yellow-50', border: 'border-[#b8860b]' },
};

export const PRODUCTS: Product[] = [
  {
    id: 'custom-tee',
    isActive: true,
    name: { en: 'Custom Design Tee', kh: 'អាវយឺតរចនាដោយខ្លួនឯង', cn: '自定义设计T恤' },
    description: { en: 'Create your own masterpiece with AI-powered design tools. High-quality cotton blend for comfort.', kh: 'បង្កើតស្នាដៃផ្ទាល់ខ្លួនរបស់អ្នកជាមួយ AI។ ក្រណាត់កប្បាសគុណភាពខ្ពស់។', cn: '用 AI 创造您自己的杰作。高品质棉混纺。' },
    price: 25.00, typicalPrice: 35.00,
    category: 'Custom', subCategory: 'Clothing', itemType: 'Shirts',
    brand: 'Master Studio', material: 'Cotton',
    rating: 5.0, reviews: 12, stock: 999,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=800&q=80'
    ],
    colors: ['White', 'Black'], sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    features: {
      en: ['100% Organic Cotton', 'AI Design Integration', 'Premium Stitching'],
      kh: ['កប្បាសសរីរាង្គ ១០០%', 'រចនាដោយ AI', 'ថ្នេរដេរគុណភាពខ្ពស់'],
      cn: ['100% 有机棉', 'AI 设计集成', '优质缝制']
    }
  },
  {
    id: '1',
    isActive: true,
    name: { en: 'Signature Khmer Cotton Shirt', kh: 'អាវសាច់ក្រណាត់កប្បាសខ្មែរ', cn: '高棉棉质签名衬衫' },
    description: { en: 'Hand-woven premium cotton shirt. Breathable and durable for tropical weather.', kh: 'អាវកប្បាសត្បាញដោយដៃ។ ខ្យល់ចេញចូលបានល្អ និងប្រើបានយូរ។', cn: '手工编织的高级棉衬衫。透气耐用。' },
    price: 15.00, typicalPrice: 25.00,
    category: 'Men', subCategory: 'Clothing', itemType: 'Shirts',
    brand: 'Khmer Cotton', material: 'Cotton',
    rating: 4.9, reviews: 1250, stock: 120, isBestSeller: true,
    isFlashSale: true,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598033129183-c4f50c7176c8?auto=format&fit=crop&w=800&q=80'
    ],
    colors: ['White', 'Blue'], sizes: ['S', 'M', 'L', 'XL'],
    features: {
      en: ['Hand-Woven', 'Ethically Sourced', 'Breathable Fabric'],
      kh: ['ត្បាញដោយដៃ', 'ប្រភពសីលធម៌', 'សាច់ក្រណាត់ត្រជាក់'],
      cn: ['手工编织', '来源道德', '透气面料']
    }
  },
  {
    id: '2',
    isActive: true,
    name: { en: 'Nike Air Max Elite', kh: 'ស្បែកជើង Nike Air Max Elite', cn: 'Nike Air Max 精英版' },
    description: { en: 'Revolutionary comfort for everyday use. High performance and sleek aesthetic.', kh: 'ផាសុកភាពសម្រាប់ការប្រើប្រាស់ប្រចាំថ្ងៃ។ គុណភាពខ្ពស់។', cn: '日常使用的革命性舒适感。高性能。' },
    price: 145.00, typicalPrice: 180.00,
    category: 'Men', subCategory: 'Shoes', itemType: 'Shoes',
    brand: 'Nike', material: 'Textile',
    rating: 4.8, reviews: 450, stock: 35, isNewArrival: true,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512374382149-4332c6c021f1?auto=format&fit=crop&w=800&q=80'
    ],
    colors: ['Red', 'Black'], sizes: ['8', '9', '10', '11'],
    features: {
      en: ['Air Cushioning', 'Lightweight', 'High Traction Sole'],
      kh: ['បច្ចេកវិទ្យា Air', 'ទម្ងន់ស្រាល', 'ស្វិតជាប់ល្អ'],
      cn: ['气垫', '轻便', '高抓地力鞋底']
    }
  },
  {
    id: '4',
    isActive: true,
    name: { en: 'Urban Oversized Hoodie', kh: 'អាវរងាស្ទីល Urban', cn: '都市大码连帽衫' },
    description: { en: 'Premium heavy-weight cotton hoodie for a modern streetwear look.', kh: 'អាវរងាសាច់ក្រាស់ គុណភាពខ្ពស់ ស្ទីល Streetwear។', cn: '优质重型棉质连帽衫，现代街头服饰。' },
    price: 45.00, typicalPrice: 60.00,
    category: 'Men', subCategory: 'Clothing', itemType: 'Hoodies',
    brand: 'Master Studio', material: 'Cotton',
    rating: 4.7, reviews: 85, stock: 50, isNewArrival: true,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80',
    colors: ['Grey', 'Black'], sizes: ['M', 'L', 'XL'],
  },
  {
    id: '5',
    isActive: true,
    name: { en: 'Minimalist Linen Shirt', kh: 'អាវសាច់ក្រណាត់លីណិន', cn: '简约亚麻衬衫' },
    description: { en: 'Lightweight and breathable linen for the perfect summer aesthetic.', kh: 'សាច់ក្រណាត់លីណិន ស្រាល និងត្រជាក់ សម្រាប់រដូវក្តៅ។', cn: '轻质透气亚麻，完美夏日审美。' },
    price: 35.00, typicalPrice: 45.00,
    category: 'Women', subCategory: 'Clothing', itemType: 'Shirts',
    brand: 'Khmer Cotton', material: 'Linen',
    rating: 4.9, reviews: 320, stock: 75, isBestSeller: true,
    image: 'https://images.unsplash.com/photo-1594932224010-74f43a185623?auto=format&fit=crop&w=800&q=80',
    colors: ['Beige', 'White'], sizes: ['S', 'M', 'L'],
  },
  {
    id: '6',
    isActive: true,
    name: { en: 'Techwear Cargo Pants', kh: 'ខោ Cargo ស្ទីល Techwear', cn: 'Techwear 工装裤' },
    description: { en: 'Weather-resistant cargo pants with multiple utility pockets.', kh: 'ខោ Cargo ធន់នឹងអាកាសធាតុ ជាមួយហោប៉ៅច្រើន។', cn: '耐候工装裤，带多个实用口袋。' },
    price: 65.00, typicalPrice: 85.00,
    category: 'Men', subCategory: 'Clothing', itemType: 'Pants',
    brand: 'Master Studio', material: 'Synthetic',
    rating: 4.6, reviews: 150, stock: 40,
    image: 'https://images.unsplash.com/photo-1519176311815-38596646549a?auto=format&fit=crop&w=800&q=80',
    colors: ['Black', 'Olive'], sizes: ['30', '32', '34'],
  },
  {
    id: '7',
    isActive: true,
    name: { en: 'Boho Summer Dress', kh: 'រ៉ូបស្ទីល Boho', cn: '波西米亚夏日连衣裙' },
    description: { en: 'Flowy and elegant dress for beach days and garden parties.', kh: 'រ៉ូបឆើតឆាយ និងទាន់សម័យ សម្រាប់ដើរលេងសមុទ្រ។', cn: '飘逸优雅的连衣裙，适合海滩和花园派对。' },
    price: 40.00, typicalPrice: 55.00,
    category: 'Women', subCategory: 'Clothing', itemType: 'Dresses',
    brand: 'Zara', material: 'Rayon',
    rating: 4.8, reviews: 95, stock: 60, isNewArrival: true,
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
    colors: ['Floral', 'Blue'], sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: '8',
    isActive: true,
    name: { en: 'Graphic Streetwear Tee', kh: 'អាវយឺតស្ទីល Streetwear', cn: '印花街头T恤' },
    description: { en: 'Unique graphic design printed on 100% premium heavy cotton.', kh: 'ការរចនាក្រាហ្វិកប្លែក លើសាច់ក្រណាត់កប្បាសក្រាស់។', cn: '100% 优质重磅棉上印有独特的图形设计。' },
    price: 28.00, typicalPrice: 38.00,
    category: 'Men', subCategory: 'Clothing', itemType: 'Shirts',
    brand: 'Master Studio', material: 'Cotton',
    rating: 4.5, reviews: 210, stock: 100,
    image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
    colors: ['White', 'Black'], sizes: ['S', 'M', 'L', 'XL'],
  }
];

export const TRANSLATIONS: Record<Language, TranslationStrings> = {
  [Language.EN]: {
    heroTitle: 'Global Style with AI Precision',
    heroSub: 'The ultimate destination for all your wearable needs.',
    ctaShopNow: 'Explore Shop',
    categories: 'Departments',
    featuredProducts: 'New & Noteworthy',
    addToCart: 'Add to Bag',
    checkout: 'Checkout',
    cartEmpty: 'Bag is empty.',
    total: 'Total',
    paymentMethod: 'Pay with',
    adminTitle: 'Admin Dashboard',
    searchPlaceholder: 'Search anything...',
    howItWorks: 'How it works',
    benefits: 'Why us',
    faq: 'FAQ',
    bulkSavings: 'Wholesale',
    testimonials: 'Testimonials',
    customDesignCta: 'Custom Design',
    promptAssistantTitle: 'Master Prompt',
    promptAssistantSub: 'Explain your idea, we expand it.',
    trackOrderTitle: 'Track Order',
    trackOrderSub: 'Real-time status updates.',
    trackPlaceholder: 'Order ID...',
    trackCta: 'Track',
    flashSaleTitle: 'Flash Sale',
    flashSaleSub: 'Up to 60% off limited items.',
    endsIn: 'Ends in',
    accountLabel: 'Account / Login',
    loginLabel: 'Login',
    registerLabel: 'Register',
    personalInfoLabel: 'Profile',
    orderHistoryLabel: 'Order History',
    logoutLabel: 'Logout',
    emailPhoneLabel: 'Email / Phone',
    passwordLabel: 'Password',
    forgotPasswordLabel: 'Forgot Password?',
    confirmPasswordLabel: 'Confirm Password',
    alreadyHaveAccountLabel: 'Already have an account?',
    fullNameLabel: 'Full Name',
    addressLabel: 'Address',
    editInfoLabel: 'Edit Profile',
    orderNumberLabel: 'Order Number',
    dateLabel: 'Date',
    statusLabel: 'Status',
    totalPriceLabel: 'Total Price',
    viewDetailsLabel: 'View Details',
    statusPending: 'Pending',
    statusShipping: 'Shipping',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    adminLogin: 'Admin Login',
    adminLogout: 'Admin Logout',
    productManagement: 'Product Management',
    orderManagement: 'Order Management',
    userManagement: 'User Management',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    allOrders: 'All Orders',
    revenue: 'Total Revenue',
    topProducts: 'Best Sellers'
  },
  [Language.KH]: {
    heroTitle: 'ស្ទីលពិភពលោកជាមួយ AI',
    heroSub: 'គោលដៅចុងក្រោយសម្រាប់តម្រូវការប្រចាំថ្ងៃរបស់អ្នក។',
    ctaShopNow: 'ទិញឥឡូវនេះ',
    categories: 'ប្រភេទ',
    featuredProducts: 'ផលិតផលថ្មីៗ',
    addToCart: 'បន្ថែមទៅកន្ត្រក',
    checkout: 'ទូទាត់ប្រាក់',
    cartEmpty: 'កន្ត្រករបស់អ្នកទទេស្អាត។',
    total: 'សរុប',
    paymentMethod: 'ទូទាត់តាម',
    adminTitle: 'ផ្ទាំងគ្រប់គ្រងអ្នកគ្រប់គ្រង',
    searchPlaceholder: 'ស្វែងរកអ្វីៗគ្រប់យ៉ាង...',
    howItWorks: 'របៀបបញ្ជាទិញ',
    benefits: 'អត្ថប្រយោជន៍',
    faq: 'សំណួរដែលសួរញឹកញាប់',
    bulkSavings: 'ការទិញដុំ',
    testimonials: 'មតិអតិថិជន',
    customDesignCta: 'រចនាជាមួយ AI',
    promptAssistantTitle: 'ជំនួយការ Prompt',
    promptAssistantSub: 'រៀបរាប់ពីអ្វីដែលអ្នកចង់បាន។',
    trackOrderTitle: 'តាមដានការបញ្ជាទិញ',
    trackOrderSub: 'ពិនិត្យស្ថានភាពតាមពេលវេលាជាក់ស្តែង។',
    trackPlaceholder: 'លេខសម្គាល់ការបញ្ជាទិញ...',
    trackCta: 'តាមដាន',
    flashSaleTitle: 'ការលក់បញ្ចុះតម្លៃពិសេស',
    flashSaleSub: 'បញ្ចុះតម្លៃរហូតដល់ ៦០%។',
    endsIn: 'បញ្ចប់ក្នុងរយៈពេល',
    accountLabel: 'គណនីអ្នកប្រើ',
    loginLabel: 'ចូលគណនី',
    registerLabel: 'ចុះឈ្មោះ',
    personalInfoLabel: 'ព័ត៌មានផ្ទាល់ខ្លួន',
    orderHistoryLabel: 'ប្រវត្តិបញ្ជាទិញ',
    logoutLabel: 'ចាកចេញ',
    emailPhoneLabel: 'អ៊ីមែល / លេខទូរស័ព្ទ',
    passwordLabel: 'ពាក្យសម្ងាត់',
    forgotPasswordLabel: 'ភ្លេចពាក្យសម្ងាត់?',
    confirmPasswordLabel: 'បញ្ជាក់ពាក្យសម្ងាត់',
    alreadyHaveAccountLabel: 'មានគណនីរួចហើយ?',
    fullNameLabel: 'ឈ្មោះពេញ',
    addressLabel: 'អាសយដ្ឋាន',
    editInfoLabel: 'កែប្រែ Profile',
    orderNumberLabel: 'លេខបញ្ជាទិញ',
    dateLabel: 'កាលបរិច្ឆេទ',
    statusLabel: 'ស្ថានភាព',
    totalPriceLabel: 'តម្លៃសរុប',
    viewDetailsLabel: 'មើលលម្អិត',
    statusPending: 'កំពុងដំណើរការ',
    statusShipping: 'កំពុងដឹកជញ្ជូន',
    statusCompleted: 'បានបញ្ចប់',
    statusCancelled: 'បានបោះបង់',
    adminLogin: 'ចូលគ្រប់គ្រង',
    adminLogout: 'ចាកចេញពី Admin',
    productManagement: 'គ្រប់គ្រងផលិតផល',
    orderManagement: 'គ្រប់គ្រងការបញ្ជាទិញ',
    userManagement: 'គ្រប់គ្រងអ្នកប្រើប្រាស់',
    addProduct: 'បន្ថែមផលិតផល',
    editProduct: 'កែប្រែផលិតផល',
    deleteProduct: 'លុបផលិតផល',
    allOrders: 'មើលបញ្ជាទិញទាំងអស់',
    revenue: 'ចំណូលសរុប',
    topProducts: 'Product លក់ដាច់'
  },
  [Language.CN]: {
    heroTitle: '全球风尚 智能定义',
    heroSub: '满足您所有佩戴需求的一站式目的地。',
    ctaShopNow: '探索商店',
    categories: '部门',
    featuredProducts: '新品推荐',
    addToCart: '加入购物袋',
    checkout: '结账',
    cartEmpty: '购物袋为空。',
    total: '总计',
    paymentMethod: '支付方式',
    adminTitle: '管理后台',
    searchPlaceholder: '搜索...',
    howItWorks: '运作流程',
    benefits: '选择我们',
    faq: '常见问题',
    bulkSavings: '批发',
    testimonials: '客户评价',
    customDesignCta: '定制设计',
    promptAssistantTitle: '大师级提示词',
    promptAssistantSub: '解释您的创意，我们为您扩展。',
    trackOrderTitle: '追踪订单',
    trackOrderSub: '实时状态更新。',
    trackPlaceholder: '订单号...',
    trackCta: '追踪',
    flashSaleTitle: '限时闪购',
    flashSaleSub: '精选商品低至4折。',
    endsIn: '距离结束还有',
    accountLabel: '账户 / 登录',
    loginLabel: '登录',
    registerLabel: '注册',
    personalInfoLabel: '个人信息',
    orderHistoryLabel: '订单历史',
    logoutLabel: '注销',
    emailPhoneLabel: '邮箱 / 电话',
    passwordLabel: '密码',
    forgotPasswordLabel: '忘记密码？',
    confirmPasswordLabel: '确认密码',
    alreadyHaveAccountLabel: '已有账户？',
    fullNameLabel: '全名',
    addressLabel: '地址',
    editInfoLabel: '编辑信息',
    orderNumberLabel: '订单号',
    dateLabel: '日期',
    statusLabel: '状态',
    totalPriceLabel: '总价',
    viewDetailsLabel: '查看详情',
    statusPending: '待处理',
    statusShipping: '运输中',
    statusCompleted: '已完成',
    statusCancelled: '已取消',
    adminLogin: '管理员登录',
    adminLogout: '注销管理员',
    productManagement: '产品管理',
    orderManagement: '订单管理',
    userManagement: '用户管理',
    addProduct: '添加产品',
    editProduct: '编辑产品',
    deleteProduct: '删除产品',
    allOrders: '所有订单',
    revenue: '总收入',
    topProducts: '畅销产品'
  }
};
